### ISSUE TITLE
TypeScript Support/Version

### ISSUE THREAD

**Issue by ghost** [ppauel/djs-template#3]
I am wondering if there will be a version or support added to turn this project into a TypeScript Project. I have noticed that there is not many good Discord.js TypeScript Project Templates on GitHub and I think it would be cool if this project had a TS version.

**Comment by ppauel** [comment]
Have actually thought about it myself. I'm only working with TypeScript at the moment, so I might as well create a TS template.

**Comment by ghost** [comment]
> Have actually thought about it myself. I'm only working with TypeScript at the moment, so I might as well create a TS template.

Awesome! I am also currently only working with TypeScript. And I currently have a bot using this template however, I have been having trouble converting it to TypeScript because of the lack of good TS Discord bot templates.

**Comment by ghost** [comment]
Closing this issue because of the creation of the repository https://github.com/ppauel/typescript-discord-bot
